theme: osuny-hugo-theme

## LANGUAGE
defaultContentLanguage: fr
languageCode: fr

## ADVANCED
paginate: 18
enableRobotsTXT: true

## MODULE
module:
  _merge: deep

deployment:
  targets:
    - name: "production"
      URL: "s3://b054f96385130aab1c66e748250982bd97291f7c019eb0a8d4e8db435165d797?endpoint=garage.deuxfleurs.fr&s3ForcePathStyle=true&region=garage"

## PARAMS
params:
  _merge: deep
  carbon:
    home: 0.08
    legal: 0.04
  cookie_banner:
    enable: false
