theme: osuny-hugo-theme

## LANGUAGE
defaultContentLanguage: fr
languageCode: fr

## ADVANCED
paginate: 18
enableRobotsTXT: true

## MODULE
module:
  _merge: deep

## PARAMS
params:
  _merge: deep
  carbon:
    home: 0.21
    legal: 0.1
  cookie_banner:
    enable: false
